### ISSUE TITLE
How to add subreddits?

### ISSUE THREAD

**Issue by seanvree** [plexinc-plugins/RedditVideos.bundle#6]
Am I missing something or how do you add custom subreddits?

**Comment by sander1** [comment]
@seagullcanfly?

**Comment by seanvree** [comment]
So, I saw that you have to do it thru the plex app (I tested on android). 

Still seems a bit buggy, but I got it working by manually adding them via the PLEX app on Android. 

Does NOT seem to work from the Web GUI (I tested on Chrome running on Windows 10)

**Comment by seagullcanfly** [comment]
I'll try to look into this soon.  It used to work on the web app but no
longer does.
